// Code generated by gen_packet_codec.go; DO NOT EDIT.
package packet

import (
	"io"
)

// Source: login.go
var LoginServerboundRegistry = map[int32]func() Packet{
	0: func() Packet { return &LoginStart{} },
	1: func() Packet { return &EncryptionResponse{} },
	3: func() Packet { return &LoginAcknowledge{} },
}
var LoginClientboundRegistry = map[int32]func() Packet{
	0: func() Packet { return &LoginDisconnect{} },
	1: func() Packet { return &EncryptionRequest{} },
	2: func() Packet { return &LoginSuccess{} },
	3: func() Packet { return &SetCompression{} },
}

func (p LoginStart) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteString(w, p.Name); err != nil { return }
	if err = WriteUUID(w, p.PlayerUUID); err != nil { return }
	return
}

func (p *LoginStart) Decode(r io.Reader) (err error) {
	if p.Name, err = ReadString(r); err != nil { return }
	if p.PlayerUUID, err = ReadUUID(r); err != nil { return }
	return nil
}

func (p EncryptionResponse) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WritePrefixedArray(w, p.SharedSecret, WriteByte); err != nil { return }
	if err = WritePrefixedArray(w, p.VerifyToken, WriteByte); err != nil { return }
	return
}

func (p *EncryptionResponse) Decode(r io.Reader) (err error) {
	if p.SharedSecret, err = ReadPrefixedArray(r, ReadByte); err != nil { return }
	if p.VerifyToken, err = ReadPrefixedArray(r, ReadByte); err != nil { return }
	return nil
}

func (p LoginAcknowledge) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	return
}

func (p *LoginAcknowledge) Decode(r io.Reader) (err error) {
	return nil
}

func (p LoginDisconnect) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteString(w, p.Reason); err != nil { return }
	return
}

func (p *LoginDisconnect) Decode(r io.Reader) (err error) {
	if p.Reason, err = ReadString(r); err != nil { return }
	return nil
}

func (p EncryptionRequest) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteString(w, p.ServerID); err != nil { return }
	if err = WritePrefixedArray(w, p.PublicKey, WriteByte); err != nil { return }
	if err = WritePrefixedArray(w, p.VerifyToken, WriteByte); err != nil { return }
	if err = WriteBoolean(w, p.ShouldAuth); err != nil { return }
	return
}

func (p *EncryptionRequest) Decode(r io.Reader) (err error) {
	if p.ServerID, err = ReadString(r); err != nil { return }
	if p.PublicKey, err = ReadPrefixedArray(r, ReadByte); err != nil { return }
	if p.VerifyToken, err = ReadPrefixedArray(r, ReadByte); err != nil { return }
	if p.ShouldAuth, err = ReadBoolean(r); err != nil { return }
	return nil
}

func (p LoginSuccess) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteUUID(w, p.UUID); err != nil { return }
	if err = WriteString(w, p.Username); err != nil { return }
	if err = WritePrefixedArray(w, p.Properties, writeGameProfileProperty); err != nil { return }
	if err = WriteBoolean(w, p.StrictErrHandling); err != nil { return }
	return
}

func (p *LoginSuccess) Decode(r io.Reader) (err error) {
	if p.UUID, err = ReadUUID(r); err != nil { return }
	if p.Username, err = ReadString(r); err != nil { return }
	if p.Properties, err = ReadPrefixedArray(r, readGameProfileProperty); err != nil { return }
	if p.StrictErrHandling, err = ReadBoolean(r); err != nil { return }
	return nil
}

func (p SetCompression) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteVarInt(w, p.Threshold); err != nil { return }
	return
}

func (p *SetCompression) Decode(r io.Reader) (err error) {
	if p.Threshold, err = ReadVarInt(r); err != nil { return }
	return nil
}

// Source: packet.go

func (p HandshakePacket) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteVarInt(w, p.ProtocolVersion); err != nil { return }
	if err = WriteString(w, p.ServerAddr); err != nil { return }
	if err = WriteUnsignedShort(w, p.ServerPort); err != nil { return }
	if err = WriteVarInt(w, p.RequestType); err != nil { return }
	return
}

func (p *HandshakePacket) Decode(r io.Reader) (err error) {
	if p.ProtocolVersion, err = ReadVarInt(r); err != nil { return }
	if p.ServerAddr, err = ReadString(r); err != nil { return }
	if p.ServerPort, err = ReadUnsignedShort(r); err != nil { return }
	if p.RequestType, err = ReadVarInt(r); err != nil { return }
	return nil
}

// Source: status.go
var StatusServerboundRegistry = map[int32]func() Packet{
	0: func() Packet { return &StatusReqPacket{} },
	1: func() Packet { return &PingReqPacket{} },
}
var StatusClientboundRegistry = map[int32]func() Packet{
	0: func() Packet { return &StatusRespPacket{} },
}

func (p StatusReqPacket) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	return
}

func (p *StatusReqPacket) Decode(r io.Reader) (err error) {
	return nil
}

func (p PingReqPacket) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteLong(w, p.Timestamp); err != nil { return }
	return
}

func (p *PingReqPacket) Decode(r io.Reader) (err error) {
	if p.Timestamp, err = ReadLong(r); err != nil { return }
	return nil
}

func (p StatusRespPacket) Encode(w io.Writer) (err error) {
	if err = WriteVarInt(w, p.ID()); err != nil { return }
	if err = WriteString(w, p.Response); err != nil { return }
	return
}

func (p *StatusRespPacket) Decode(r io.Reader) (err error) {
	if p.Response, err = ReadString(r); err != nil { return }
	return nil
}

